name: SoH Project Runner

on:
  push:
    branches: 
      - main

jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: git pull

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run Streamlit app
        run: streamlit run app.py --server.runOnSave false --server.fileWatcherType none
