name: SoH Project Runner

on:
  push:
    branches: 
      - main

jobs:
  production-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 
      

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            scripts/install.sh
          fi

      - name: Run Streamlit app
        run: scripts/run.sh
